# Generated by Django 5.0.4 on 2024-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'זכר'), ('female', 'נקבה'), ('other', 'אחר')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='life_status',
            field=models.CharField(choices=[('single', 'רווק'), ('marriage', 'נשוי/ה'), ('divorce', 'גרוש/ה')], max_length=50),
        ),
    ]
