# Generated by Django 5.0.4 on 2024-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_gender_alter_customuser_life_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateField(default='2022-02-22'),
            preserve_default=False,
        ),
    ]
