# Generated by Django 4.2.7 on 2024-07-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_num_of_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה'), ('נקבה', 'נקבה')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='life_status',
            field=models.CharField(choices=[('רווק/ה', 'רווק/ה'), ('נשוי/ה', 'נשוי/ה'), ('גרוש/ה', 'גרוש/ה')], max_length=50),
        ),
    ]
