# Generated by Django 4.2.7 on 2024-07-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_gender_alter_customuser_life_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה'), ('אחר', 'אחר')], max_length=10),
        ),
    ]
