# Generated by Django 5.0.4 on 2024-05-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_family_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='total_income',
        ),
    ]
