# Generated by Django 5.0.4 on 2024-05-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_family_total_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='family_name',
        ),
    ]
