# Generated by Django 5.0.4 on 2024-05-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_family_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='id',
            new_name='family_id',
        ),
    ]
