# Generated by Django 5.0.4 on 2024-05-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_business_customuser_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
