# Generated by Django 5.0.4 on 2024-06-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
    ]
