# Generated by Django 5.0.4 on 2024-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
