# Generated by Django 5.0.4 on 2024-06-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_remove_creditcard_family_id_remove_debts_family_id_and_more'),
        ('users', '0019_alter_customuser_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
