# Generated by Django 5.0.4 on 2024-06-28 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(choices=[('no_card', 'no_card'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American Express', 'American Express'), ('Diners', 'Diners')], max_length=50)),
                ('day_of_charge', models.CharField(choices=[('2', '2'), ('10', '10'), ('15', '15'), ('none', 'none')], max_length=50)),
                ('credit_type', models.TextField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50)),
                ('line_of_credit', models.FloatField(blank=True, null=True)),
                ('last_four_digits', models.TextField(max_length=4)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('mortgage', 'משכנתא'), ('goverment', 'ממשלתית'), ('loan', 'הלוואה'), ('business', 'עסק'), ('medical', 'רפואי'), ('car', 'משכון רכב')], max_length=50)),
                ('name', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('line_of_debt', models.FloatField()),
                ('interest', models.FloatField()),
                ('starting_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'כרטיס אשראי'), ('direct_debit', 'הוראת קבע'), ('transaction', 'העברה בנקאית'), ('cash', 'מזומן'), ('check', 'צ׳ק')], max_length=50)),
                ('expense_type', models.CharField(choices=[('regular_expense', 'הוצאה רגילה'), ('irregular_expense', 'הוצאה לא רגילה')], max_length=50)),
                ('date_and_time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.TextField(choices=[('supermarket', 'סופר'), ('restaurant', 'מסעדה'), ('tech', 'טכנולוגיה'), ('dress_and_shoes', 'הלבשה והנעלה'), ('fuel', 'דלק'), ('loan', 'הלוואה'), ('debt', 'חוב'), ('gift', 'מתנה')], max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('salary', 'משכורת'), ('allowance', 'קצבה'), ('other', 'אחר')], max_length=50)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saving_type', models.CharField(choices=[('health', 'בריאות'), ('business', 'עסקים'), ('regular', 'רגיל'), ('education', 'השכלה'), ('other', 'אחר')], max_length=50)),
                ('interest', models.FloatField()),
                ('amount', models.FloatField()),
                ('starting_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
