# Generated by Django 5.0.4 on 2024-04-26 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(choices=[('type1', 'VISA'), ('type2', 'MASTERCARD'), ('type3', '15')], max_length=50)),
                ('day_of_charge', models.CharField(choices=[('type1', '1'), ('type2', '10'), ('type3', '15')], max_length=50)),
                ('credit_type', models.TextField(choices=[('type1', 'Debit'), ('type2', 'Credit'), ('type3', '')], max_length=50)),
                ('line_of_credit', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('line_of_debt', models.FloatField()),
                ('interest', models.FloatField()),
                ('amount_left', models.FloatField()),
                ('num_of_months', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('CreditCard', 'כרטיס אשראי'), ('type2', 'הוראת קבע'), ('type3', 'העברה בנקאית'), ('type4', 'מזומן'), ('type5', 'צ׳ק')], max_length=10)),
                ('expense_type', models.CharField(choices=[('RegularExpenses', 'סוג1'), ('IrregularExpenses', 'סוג2')], max_length=50)),
                ('date', models.DateTimeField()),
                ('name', models.TextField(max_length=100)),
                ('category', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_income', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('num_of_months', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('type1', 'Salary'), ('type2', 'סוג2'), ('type3', 'Other')], max_length=50)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saving_type', models.CharField(choices=[('type1', 'סוג1'), ('type2', 'סוג2'), ('type3', 'סוג3')], max_length=50)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
