# Generated by Django 5.0.4 on 2024-04-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='credit_cards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.creditcard'),
        ),
        migrations.AddField(
            model_name='business',
            name='Debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.debt'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='backend.creditcard'),
        ),
        migrations.AddField(
            model_name='business',
            name='expenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.expenses'),
        ),
        migrations.AddField(
            model_name='family',
            name='credit_cards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.creditcard'),
        ),
        migrations.AddField(
            model_name='family',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.debt'),
        ),
        migrations.AddField(
            model_name='family',
            name='last_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='loans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loan'),
        ),
        migrations.AddField(
            model_name='business',
            name='loans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loan'),
        ),
        migrations.AddField(
            model_name='business',
            name='revenues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='backend.revenue'),
        ),
        migrations.AddField(
            model_name='business',
            name='savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.saving'),
        ),
    ]
