# Generated by Django 5.0.4 on 2024-04-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='Loans',
        ),
    ]
