# Generated by Django 5.0.4 on 2024-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_loan_loans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='day_of_charge',
            field=models.CharField(choices=[('type1', '2'), ('type2', '10'), ('type3', '15')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.TextField(choices=[('supermarket', 'סופר'), ('restaurant', 'מסעדה'), ('tech', 'טכנולוגיה'), ('dress and shoes', 'הלבשה והנעלה'), ('fuel', 'דלק'), ('loan', 'הלוואה'), ('debt', 'חוב')], max_length=50),
        ),
    ]
