# Generated by Django 4.2.7 on 2024-07-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_creditcard_day_of_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.TextField(choices=[('סופר', 'סופר'), ('מסעדה', 'מסעדה'), ('טכנולוגיה', 'טכנולוגיה'), ('הלבשה והנעלה', 'הלבשה והנעלה'), ('דלק', 'דלק'), ('הלוואה', 'הלוואה'), ('חוב', 'חוב'), ('מתנה', 'מתנה'), ('אחר', 'אחר')], max_length=50),
        ),
    ]
