# Generated by Django 5.0.4 on 2024-04-30 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_creditcard_user_id_debt_user_id_expenses_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('line_of_debt', models.FloatField()),
                ('interest', models.FloatField()),
                ('amount_left', models.FloatField()),
                ('num_of_months', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='Debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.debts'),
        ),
        migrations.AlterField(
            model_name='family',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.debts'),
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
