# Generated by Django 5.0.4 on 2024-05-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_expenses_category_delete_family'),
        ('users', '0011_rename_id_family_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CreditCard', to='users.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debts',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='users.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='users.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saving',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='users.family'),
            preserve_default=False,
        ),
    ]
