# Generated by Django 4.2.7 on 2024-05-05 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_rename_id_family_family_id'),
        ('backend', '0010_creditcard_family_id_debts_family_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saving',
            new_name='Savings',
        ),
    ]
