# Generated by Django 4.2.7 on 2024-05-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_saving_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts',
            name='amount_left',
        ),
    ]
