# Generated by Django 4.2.7 on 2024-05-05 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_rename_id_family_family_id'),
        ('backend', '0012_remove_debts_amount_left'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revenue',
            new_name='Revenues',
        ),
    ]
