# Generated by Django 4.2.7 on 2024-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_revenue_revenues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='line_of_credit',
            field=models.FloatField(default=None),
        ),
    ]
