# Generated by Django 4.2.7 on 2024-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_creditcard_line_of_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('RegularExpenses', 'הוצאה רגילה'), ('IrregularExpenses', 'הוצאה לא רגילה')], max_length=50),
        ),
    ]
