# Generated by Django 4.2.7 on 2024-05-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_expenses_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='credit_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='backend.creditcard'),
        ),
    ]
