# Generated by Django 4.2.7 on 2024-05-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_expenses_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='credit_card',
        ),
    ]
