# Generated by Django 4.2.7 on 2024-05-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_expenses_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='credit_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='backend.creditcard'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='day_of_charge',
            field=models.CharField(choices=[('type1', '2'), ('type2', '10'), ('type3', '15')], default='none', max_length=50),
        ),
    ]
