# Generated by Django 4.2.7 on 2024-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_expenses_credit_card_alter_creditcard_day_of_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='day_of_charge',
            field=models.CharField(choices=[('type1', '2'), ('type2', '10'), ('type3', '15'), ('type4', 'none')], max_length=50),
        ),
    ]
