# Generated by Django 4.2.7 on 2024-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_creditcard_day_of_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='line_of_credit',
            field=models.FloatField(default=None, null=True),
        ),
    ]
