# Generated by Django 4.2.7 on 2024-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_creditcard_line_of_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='line_of_credit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
