# Generated by Django 4.2.7 on 2024-05-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_creditcard_line_of_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
