# Generated by Django 5.0.4 on 2024-06-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_debts_starting_date_loans_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts',
            name='num_of_months',
        ),
    ]
