# Generated by Django 5.0.4 on 2024-06-06 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_debts_num_of_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='finish_date',
            field=models.DateField(default=datetime.date(2013, 1, 1)),
            preserve_default=False,
        ),
    ]
