# Generated by Django 5.0.4 on 2024-06-06 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_debts_debt_type_delete_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='finish_date',
            field=models.DateField(default=datetime.date(2013, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savings',
            name='interest',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savings',
            name='starting_date',
            field=models.DateField(default=datetime.date(2013, 1, 1)),
            preserve_default=False,
        ),
    ]
