# Generated by Django 5.0.4 on 2024-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_savings_finish_date_savings_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.TextField(choices=[('type1', 'VISA'), ('type2', 'MASTERCARD'), ('type3', 'American Express')], max_length=50),
        ),
    ]
