# Generated by Django 5.0.4 on 2024-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_creditcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.TextField(choices=[('supermarket', 'סופר'), ('restaurant', 'מסעדה'), ('tech', 'טכנולוגיה'), ('dress_and_shoes', 'הלבשה והנעלה'), ('fuel', 'דלק'), ('loan', 'הלוואה'), ('debt', 'חוב'), ('gift', 'מתנה')], max_length=50),
        ),
    ]
