# Generated by Django 5.0.4 on 2024-06-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_expenses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('regular_expenses', 'הוצאה רגילה'), ('irregular_expenses', 'הוצאה לא רגילה')], max_length=50),
        ),
    ]
