# Generated by Django 5.0.4 on 2024-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_creditcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='last_four_digits',
            field=models.TextField(default=1111, max_length=100),
            preserve_default=False,
        ),
    ]
