# Generated by Django 5.0.4 on 2024-06-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_creditcard_last_four_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=50),
            preserve_default=False,
        ),
    ]
