# Generated by Django 5.0.4 on 2024-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_creditcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
