# Generated by Django 5.0.4 on 2024-06-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_creditcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('regular_expense', 'הוצאה רגילה'), ('irregular_expense', 'הוצאה לא רגילה')], max_length=50),
        ),
    ]
