# Generated by Django 5.0.4 on 2024-06-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_expenses_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='price',
            field=models.FloatField(),
        ),
    ]
