# Generated by Django 5.0.4 on 2024-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_expenses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.TextField(choices=[('no_card', 'no card'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American Express', 'American Express'), ('Diners', 'Diners')], max_length=50),
        ),
    ]
