# Generated by Django 5.0.4 on 2024-06-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_creditcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenues',
            name='date',
            field=models.DateField(default='2024-6-5'),
            preserve_default=False,
        ),
    ]
