# Generated by Django 5.0.4 on 2024-06-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_revenues_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debts',
            old_name='debt_type',
            new_name='type',
        ),
    ]
