# Generated by Django 5.0.4 on 2024-06-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_rename_debt_type_debts_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='date',
            new_name='date_and_time',
        ),
    ]
