# Generated by Django 5.0.4 on 2024-06-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_rename_date_expenses_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.TextField(choices=[('no_card', 'no_card'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American Express', 'American Express'), ('Diners', 'Diners')], max_length=50),
        ),
        migrations.AlterField(
            model_name='debts',
            name='type',
            field=models.CharField(choices=[('משכנתא', 'mortgage'), ('goverment', 'ממשלתית'), ('loan', 'הלוואה'), ('business', 'עסק'), ('medical', 'רפואי'), ('car', 'משכון רכב')], max_length=50),
        ),
    ]
