# Generated by Django 5.0.4 on 2024-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_alter_debts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='saving_type',
            field=models.CharField(choices=[('health', 'בריאות'), ('business', 'עסקים'), ('regular', 'רגיל'), ('education', 'השכלה'), ('other', 'אחר')], max_length=50),
        ),
    ]
