# Generated by Django 5.0.4 on 2024-06-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_alter_creditcard_family_id_alter_debts_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='last_four_digits',
            field=models.TextField(max_length=4),
        ),
    ]
