# Generated by Django 5.0.4 on 2024-06-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_alter_creditcard_day_of_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='debts',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='revenues',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='family_id',
        ),
    ]
